pub enum Reg8 {
    AL,
    CL,
    DL,
    BL,
    AH,
    CH,
    DH,
    BH,
    SIL,
    DIL,
    BPL,
    SPL,
    R8B,
    R9B,
    R10B,
    R11B,
    R12B,
    R13B,
    R14B,
    R15B,
}

pub enum Reg16 {
    AX,
    BX,
    CX,
    DX,
    SI,
    DI,
    BP,
    SP,
    R8W,
    R9W,
    R10W,
    R11W,
    R12W,
    R13W,
    R14W,
    R15W,
}

pub enum Reg32 {
    EAX,
    EBX,
    ECX,
    EDX,
    ESI,
    EDI,
    EBP,
    ESP,
    R8D,
    R9D,
    R10D,
    R11D,
    R12D,
    R13D,
    R14D,
    R15D,
}

pub enum Reg64 {
    RAX,
    RBX,
    RCX,
    RDX,
    RSI,
    RDI,
    RBP,
    RSP,
    R8,
    R9,
    R10,
    R11,
    R12,
    R13,
    R14,
    R15,
}

pub enum Register {
    Reg8(Reg8),
    Reg16(Reg16),
    Reg32(Reg32),
    Reg64(Reg64),
}

pub fn Reg_to_String(reg: Register) -> String {
    let reg_str = match reg {
        Register::Reg8(reg) => match reg {
            Reg8::AL => "al".to_string(),
            Reg8::CL => "cl".to_string(),
            Reg8::DL => "dl".to_string(),
            Reg8::BL => "bl".to_string(),
            Reg8::AH => "ah".to_string(),
            Reg8::CH => "ch".to_string(),
            Reg8::DH => "dh".to_string(),
            Reg8::BH => "bh".to_string(),
            Reg8::SIL => "sil".to_string(),
            Reg8::DIL => "dil".to_string(),
            Reg8::BPL => "bpl".to_string(),
            Reg8::SPL => "spl".to_string(),
            Reg8::R8B => "r8b".to_string(),
            Reg8::R9B => "r9b".to_string(),
            Reg8::R10B => "r10b".to_string(),
            Reg8::R11B => "r11b".to_string(),
            Reg8::R12B => "r12b".to_string(),
            Reg8::R13B => "r13b".to_string(),
            Reg8::R14B => "r14b".to_string(),
            Reg8::R15B => "r15b".to_string(),
        },
        Register::Reg16(reg) => match reg {
            Reg16::AX => "ax".to_string(),
            Reg16::BX => "bx".to_string(),
            Reg16::CX => "cx".to_string(),
            Reg16::DX => "dx".to_string(),
            Reg16::SI => "si".to_string(),
            Reg16::DI => "di".to_string(),
            Reg16::BP => "bp".to_string(),
            Reg16::SP => "sp".to_string(),
            Reg16::R8W => "r8w".to_string(),
            Reg16::R9W => "r9w".to_string(),
            Reg16::R10W => "r10w".to_string(),
            Reg16::R11W => "r11w".to_string(),
            Reg16::R12W => "r12w".to_string(),
            Reg16::R13W => "r13w".to_string(),
            Reg16::R14W => "r14w".to_string(),
            Reg16::R15W => "r15w".to_string(),
        },
        Register::Reg32(reg) => match reg {
            Reg32::EAX => "eax".to_string(),
            Reg32::EBX => "ebx".to_string(),
            Reg32::ECX => "ecx".to_string(),
            Reg32::EDX => "edx".to_string(),
            Reg32::ESI => "esi".to_string(),
            Reg32::EDI => "edi".to_string(),
            Reg32::EBP => "ebp".to_string(),
            Reg32::ESP => "esp".to_string(),
            Reg32::R8D => "r8d".to_string(),
            Reg32::R9D => "r9d".to_string(),
            Reg32::R10D => "r10d".to_string(),
            Reg32::R11D => "r11d".to_string(),
            Reg32::R12D => "r12d".to_string(),
            Reg32::R13D => "r13d".to_string(),
            Reg32::R14D => "r14d".to_string(),
            Reg32::R15D => "r15d".to_string(),
        },
        Register::Reg64(reg) => match reg {
            Reg64::RAX => "rax".to_string(),
            Reg64::RBX => "rbx".to_string(),
            Reg64::RCX => "rcx".to_string(),
            Reg64::RDX => "rdx".to_string(),
            Reg64::RSI => "rsi".to_string(),
            Reg64::RDI => "rdi".to_string(),
            Reg64::RBP => "rbp".to_string(),
            Reg64::RSP => "rsp".to_string(),
            Reg64::R8 => "r8".to_string(),
            Reg64::R9 => "r9".to_string(),
            Reg64::R10 => "r10".to_string(),
            Reg64::R11 => "r11".to_string(),
            Reg64::R12 => "r12".to_string(),
            Reg64::R13 => "r13".to_string(),
            Reg64::R14 => "r14".to_string(),
            Reg64::R15 => "r15".to_string(),
        },
    };
    
    reg_str
}